import Footer from "@/components/shared/footer/Footer";
import "./globals.css";
import Navbar from "@/components/shared/Navbar";
import { getServerSession } from "next-auth";

import SessionProvider from "../components/SessionProvider";
import { ProductProvider } from "@/context/ProductContext";

export const metadata = {
  title: "NewTech",
  description: "Generated by create next app",
};

export default async function RootLayout({ children }) {
  const session = await getServerSession();
  return (
    <html lang="en" data-theme="cupcake">
      <body>
        <ProductProvider>
          <SessionProvider session={session}>
            <div>
              <Navbar />
              <div className="h-max">{children}</div>

              <Footer />
            </div>
          </SessionProvider>
        </ProductProvider>
      </body>
    </html>
  );
}
